# permissions for end users to edit databaseinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-database-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseinstance-editor-role
rules:
- apiGroups:
  - apps.leqiutong.xyz
  resources:
  - databaseinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.leqiutong.xyz
  resources:
  - databaseinstances/status
  verbs:
  - get
