# permissions for end users to view databaseinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-database-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseinstance-viewer-role
rules:
- apiGroups:
  - apps.zwjk.com
  resources:
  - databaseinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.zwjk.com
  resources:
  - databaseinstances/status
  verbs:
  - get
