---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.leqiutong.xyz
  resources:
  - databaseinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.leqiutong.xyz
  resources:
  - databaseinstances/finalizers
  verbs:
  - update
- apiGroups:
  - apps.leqiutong.xyz
  resources:
  - databaseinstances/status
  verbs:
  - get
  - patch
  - update
